name: Release

on:
  release:
    types: [published ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - run: yarn version --new-version ${TAG:1} --no-git-tag-version
        env:
          TAG: ${{ github.event.release.tag_name }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
