name: Run tests on pull request
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
      - run: yarn && yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
      - run: yarn test
        env:
          GOERLI_RPC: ${{ secrets.GOERLI_RPC }}
          GOERLI_DEPLOYER_PRIVKEY: ${{ secrets.GOERLI_DEPLOYER_PRIVKEY }}
